<div style="max-width: 900px; margin: 0 auto;">
    <?php echo $this->carousel('generic_carousel', $this->carousel, array(
        'showCaption'    => true, 
        'showIndicators' => true,
        'showControls'   => true
    )); ?>
</div>

<br>

<?php echo $this->alerts(); ?>

<div class="well">
    <?php echo $this->form; ?>
</div>

<div class="text-center">
    <?php echo $this->pagination(null, 'p', 'small'); ?>
</div>