<div class="row">
    
    <article class="col-sm-10">
        <div class="jumbotron">
            <h1>Bootstrap Library for Zend Framework</h1>
            <p>
            BootstrapZF is a library for <a href="http://www.zendframework.com/manual/1.12/en/manual.html" target="_blank">Zend Framework 1</a> 
            with components to create <a href="http://getbootstrap.com/" target="_blank">Bootstrap 3</a> elements.
            </p>
        </div>
        
        <div class="page-header">
            <h2 id="howtouse">How to use</h2>
        </div>
        
        <ol>
            <li>Download <strong>BootstrapZF</strong> and put the <code>library/Bootstrap</code> folder in your Zend Framework project's <code>library</code> folder;</li>
            <li>Download <strong>Bootstrap 3</strong> in <a href="http://getbootstrap.com/" target="_blank">http://getbootstrap.com</a> and put it in your Zend Framework project's <code>public</code> folder;</li>
            <li>Download <strong>Jquery</strong> in <a href="http://jquery.com/download/" target="_blank">http://jquery.com/download/</a> and put it in your Zend Framework project's <code>public</code> folder;</li>
            <li>Add to your <code>HTML</code> in <code>layout.phtml</code> the bootstrap and jquery css and js files. Something like:
<pre>
<?php echo $this->escape('<link href="<?php echo $this->baseUrl(\'bootstrap/css/bootstrap.min.css\'); ?>" rel="stylesheet">
<script src="<?php echo $this->baseUrl(\'jquery/1.11.1/jquery.min.js\'); ?>"></script>
<script src="<?php echo $this->baseUrl(\'bootstrap/js/bootstrap.min.js\'); ?>"></script>'); ?>
</pre>            
            </li>
            <li>Add the following lines to your <code>application.ini</code>:
<pre>
autoloaderNamespaces[] = "Bootstrap"
resources.view.helperPath.Bootstrap_View_Helper = "Bootstrap/View/Helper"
resources.frontController.actionHelperPaths.Bootstrap_Controller_Action_Helper = "Bootstrap/Controller/Action/Helper"
</pre>
        </li>
        <li>Use the library classes in your project.</li>
        </ol>

        <div class="page-header">
            <h2 id="components">Components</h2>
        </div>

        <div class="page-header"><h3 id="alerts">Alerts</h3></div>

        <p>Creates a <a href="http://getbootstrap.com/components/#alerts" target="_blank">Bootstrap's alert component</a> or a list of them.</p>

        <h4>Bootstrap_View_Helper_Alert</h4>
<pre>
<span class="text-muted">/**
 * $text        The message you want to appear
 * $type        Can be alert [default], success, info, warning or danger
 * $closeButton Set false if you do not want the close button (X) appears
 * $escape      If you want to add html tags inside the message, set false
 * $tag         If you want to change the default tag (div) to any other
 */
</span>
<strong><?php echo $this->escape('<?php echo $this->alert(\'<strong>Error! </strong> An error occurred!\', \'danger\', false, false, \'p\'); ?>'); ?></strong></pre>

        <div class="panel panel-default">
            <div class="panel-heading">Output</div>
            <div class="panel-body">
                <?php echo $this->alert('<strong>Error! </strong> An error occurred!', 'danger', false, false, 'p'); ?>
            </div>
        </div>

        <h4>Bootstrap_Controller_Action_Helper_Alerts</h4>

        <p>Add the messages in you controller action using the <code>Bootstrap_Controller_Action_Helper_Alerts</code></p>
<pre>
<span class="text-muted">/**
 * $text        The message you want to appear
 * $type        Can be alert [default], success, info, warning or danger
 * $escape      If you want to add html tags inside the message, set false
 */</span>
<span class="text-muted">//You can call the direct method</span>
<strong><?php echo $this->escape('$this->_helper->alerts(\'This is a direct message\', \'success\', true);'); ?></strong>
<span class="text-muted">//Or you can call the method AddMessage</span>
<strong><?php echo $this->escape('$this->getHelper(\'Alerts\')->addMessage(\'This is a message using addMessage().\', \'alert\', true);'); ?></strong>

<span class="text-muted">//Or you can call one of the methods for specific types of message</span>
<strong><?php echo $this->escape('$this->getHelper(\'Alerts\')->addAlert(\'<strong>Alert: </strong>This is an alert message using addAlert().\', false);'); ?></strong>
<strong><?php echo $this->escape('$this->getHelper(\'Alerts\')->addSuccess(\'<strong>Success: </strong>This is a success message using addSuccess().\', false);'); ?></strong>
<strong><?php echo $this->escape('$this->getHelper(\'Alerts\')->addInfo(\'<strong>Info: </strong>This is an info message using addInfo().\', false);'); ?></strong>
<strong><?php echo $this->escape('$this->getHelper(\'Alerts\')->addWarning(\'<strong>Success: </strong>This is an warning message using addWarning().\', false);'); ?></strong>
<strong><?php echo $this->escape('$this->getHelper(\'Alerts\')->addDanger(\'<strong>Success: </strong>This is a danger message using addDanger().\', false);'); ?></strong>
</pre>

        <h4>Bootstrap_View_Helper_Alerts</h4>
        <p>After adding the messages in the controller action with the <code>Bootstrap_Controller_Action_Helper_Alerts</code>, you call the <code>Bootstrap_View_Helper_Alerts</code> to show them:</p>
<pre>
<span class="text-muted">/**
 * $closeButton    Set false if you do not want the close button (X) appears
 * $uniqueMessages Set false if you do not want to equal messages to be filtered
 * $id             Set the <?php echo $this->escape('<ul>'); ?> id [default: 'alerts']
 */</span>
<strong><?php echo $this->escape('<?php echo $this->alerts(true, true, \'messages\'); ?>'); ?></strong>
</pre>

        <div class="panel panel-default">
            <div class="panel-heading">Output</div>
            <div class="panel-body">
                <?php echo $this->alerts(); ?>
            </div>
        </div>
        
        <div class="page-header"><h3 id="carousel">Carousel</h3></div>

        <p>Creates an image slideshow using <a href="http://getbootstrap.com/javascript/#carousel" target="_blank">Bootstrap's carousel component</a>.</p>

        <h4>Bootstrap_View_Helper_Carousel</h4>

<pre>
<strong><?php echo $this->escape('<?php $images = array(
    array(
        \'src\'           => $this->view->baseUrl(\'img/carousel-1.jpg\'),
        \'caption-title\' => \'First slide label\',
        \'caption\'       => \'Nulla vitae elit libero, a pharetra augue mollis interdum.\',
        \'alt\'           => \'900x500\'
    ),
    array(
        \'src\'           => $this->view->baseUrl(\'img/carousel-2.jpg\'),
        \'caption-title\' => \'Second slide label\',
        \'caption\'       => \'Nulla vitae elit libero, a pharetra augue mollis interdum.\',
        \'alt\'           => \'900x500\'
    ),
    array(
        \'src\'           => $this->view->baseUrl(\'img/carousel-3.jpg\'),
        \'caption-title\' => \'Third slide label\',
        \'caption\'       => \'Nulla vitae elit libero, a pharetra augue mollis interdum.\',
        \'alt\'           => \'900x500\'
    ),    
);?>'); ?></strong>

<span class="text-muted">/**
 * $id       Set the id for the div the wrappers the carousel
 * $images   Array contining the list of images with options [src, caption-title, caption, alt]
 * $options  Array width boolean options [showCaption, showIndicators, showControls], default is true for all of them
 */</span>
<?php echo $this->escape('<?php echo $this->carousel(\'generic_carousel\', $images, array(
    \'showCaption\'    => true, 
    \'showIndicators\' => true,
    \'showControls\'   => true
)); ?>'); ?>
</pre>

        <div class="panel panel-default">
            <div class="panel-heading">Output</div>
            <div class="panel-body">
                <div style="max-width: 900px; margin: 0 auto;">
                <?php echo $this->carousel('generic_carousel', $this->carousel, array(
                    'showCaption'    => true, 
                    'showIndicators' => true,
                    'showControls'   => true
                )); ?>
                </div>
            </div>
        </div>
        
        <div class="page-header"><h3 id="pagination">Pagination</h3></div>

        <p>Creates a <a href="http://getbootstrap.com/components/#pagination" target="_blank">Bootstrap's pagination</a>.</p>

        <h4>Bootstrap_View_Helper_Pagination</h4>
<pre>
<span class="text-muted">/**
 * $paginator   A Zend_Paginator object. Let it null if you have defined a $this->paginator for the view
 * $pageParam   Set the name for the page parameter [default = 'page']
 * $size        Set small (or sm) or large (or lg) if you want to change the default size
 */</span>
<strong><?php echo $this->escape('<?php echo $this->pagination(null, \'p\', \'sm\'); ?>'); ?></strong>
<strong><?php echo $this->escape('<?php echo $this->pagination(null, \'p\'); ?>'); ?></strong>
<strong><?php echo $this->escape('<?php echo $this->pagination(null, \'p\', \'lg\'); ?>'); ?></strong>
</pre>

        <div class="panel panel-default">
            <div class="panel-heading">Output</div>
            <div class="panel-body">
                <div><?php echo $this->pagination(null, 'p', 'sm'); ?></div>
                <div><?php echo $this->pagination(null, 'p'); ?></div>
                <div><?php echo $this->pagination(null, 'p', 'lg'); ?></div>
            </div>
        </div>
        
        
    <div class="page-header"><h3 id="navigation">Navigation</h3></div>

        <p>Creates a <a href="http://getbootstrap.com/components/#navbar" target="_blank">Bootstrap's navbar</a>.</p>

        <h4>Bootstrap_View_Helper_NavbarHeader</h4>
<pre>
<span class="text-muted">/**
 * $brand   Add the brand, site title or anything you want to be displayed in the navbar
 * $target  Set the name of the navbar target for the navbar toggle be used on small screens
 */</span>
<strong><?php echo $this->escape('<?php echo $this->navbarHeader(\'BootstrapZF\', \'navbar-collapse-1\'); ?>'); ?></strong>
</pre>

<div class="panel panel-default">
    <div class="panel-heading">Output</div>
    <div class="panel-body">
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <?php echo $this->navbarHeader('BootstrapZF', 'navbar-collapse-1'); ?>
            </div><!-- /.container -->
        </nav>
    </div>
</div>
        
<h4>Bootstrap_View_Helper_Navbar</h4>
<pre>
<span class="text-muted">/**
 * $container   A Zend_Navigation_Container object. This is optional if you have 
                defined a default Zend_Navigation_Container in your project
 */</span>
<strong><?php 
echo $this->escape('<?php 
$container = Zend_Registry::get(\'Zend_Navigation\')->findById(\'homepage\');
echo $this->navbar($container); 
?>'); 
?></strong>
</pre>

<div class="panel panel-default">
    <div class="panel-heading">Output</div>
    <div class="panel-body">
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse" id="navbar-collapse-1">
                    <?php echo $this->navbar(Zend_Registry::get('Zend_Navigation')->findById('homepage')); ?>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container -->
        </nav>
    </div>
</div>

<p>Now, putting them together, with aditional html:</p>
<pre>
<strong><?php echo $this->escape('<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <?php echo $this->navbarHeader(\'BootstrapZF\', \'navbar-collapse-1\'); ?>
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <?php echo $this->navbar(Zend_Registry::get(\'Zend_Navigation\')->findById(\'homepage\')); ?>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
</nav>'); ?></strong>
</pre>

<div class="panel panel-default">
    <div class="panel-heading">Output</div>
    <div class="panel-body">
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <?php echo $this->navbarHeader('BootstrapZF', 'navbar-collapse-1'); ?>
                <div class="collapse navbar-collapse" id="navbar-collapse-1">
                    <?php echo $this->navbar(Zend_Registry::get('Zend_Navigation')->findById('homepage')); ?>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container -->
        </nav>
    </div>
</div>

        
    <div class="page-header"><h3 id="breadcrumbs">Breadcrumbs</h3></div>

        <p>Creates a <a href="http://getbootstrap.com/components/#breadcrumbs" target="_blank">Bootstrap's breadcrumbs</a>.</p>

        <h4>Bootstrap_View_Helper_Breadcrumbs</h4>
        <p>Once you have configured a default Zend_Navigation in your project, you just have to call the view helper.</p>
<pre>
<strong><?php echo $this->escape('<?php echo $this->breadcrumbs(); ?>'); ?></strong>
</pre>        
        
<div class="panel panel-default">
    <div class="panel-heading">Output</div>
    <div class="panel-body">
        <?php echo $this->breadcrumbs(); ?>
    </div>
</div>
        
    <div class="page-header"><h3 id="forms">Forms</h3></div>
    

        <p>Creates a <a href="http://getbootstrap.com/css/#forms" target="_blank">Bootstrap's form</a>.</p>

        <h4>Bootstrap_Form</h4>
        <p>First, create a new form in your controller. You can choose between 
            one of the following types of form:<p>
        <ul>
            <li><code>Bootstrap_Form_Vertical</code>, creates a <a href="http://getbootstrap.com/css/#forms-example" target="_blank">Bootstrap's default form</a></li>
            <li><code>Bootstrap_Form_Horizontal</code>, creates a <a href="http://getbootstrap.com/css/#forms-horizontal" target="_blank">Bootstrap's horizontal form</a></li>
            <li><code>Bootstrap_Form_Inline</code>, creates a <a href="http://getbootstrap.com/css/#forms-inline" target="_blank">Bootstrap's inline form</a></li>
        </ul> 
        <p> Elements text, password, textarea, checkbox, multiCheckbox, radio, 
            select, button, reset, submit and file where rebuilt to fit 
            bootstrap's format.</p>
<pre>
<strong>$form = new Bootstrap_Form_Horizontal();
    
$form->addElement('hidden', 'id', array('value' => 1));
$form->addElement('text', 'text', array('label' => 'Text', 'required' => true));
$form->addElement('password', 'password', array('label' => 'Password'));
$form->addElement('textarea', 'textarea', array('label' => 'Textarea', 'rows' => 5));
$form->addElement('checkbox', 'checkme', array('label' => 'Check or not check'));

$form->addElement('multiCheckbox', 'checkallme', array(
    'label'        => 'Many options', 
    'multiOptions' => array('Option 1', 'Option 2', 'Option 3'),
    'inline'       => true
));

$form->addElement('radio', 'radiobuttons', array(
    'label'        => 'Select one', 
    'multiOptions' => array('Option 1', 'Option 2', 'Option 3'),
    'inline'       => true
));

$form->addElement('select', 'selectme', array(
    'label'        => 'Select here', 
    'multiOptions' => array('Option 1', 'Option 2', 'Option 3'),
));

$form->addElement('button', 'back', array(
    'label'      => 'Back', 
    'buttonType' => 'default',
    'iconLeft'   => 'glyphicon glyphicon-circle-arrow-left'
));

$form->addElement('reset', 'reset', array(
    'label'      => 'Reset', 
    'buttonType' => 'default',
    'icon'       => 'glyphicon glyphicon-remove-circle'
));

$form->addElement('submit', 'submit', array(
    'label'      => 'Submit', 
    'buttonType' => 'primary', 
    'iconLeft'   => 'glyphicon glyphicon-floppy-disk'
));

$form->addDisplayGroup(array('back', 'reset', 'submit'), 'buttons');</strong>
</pre>   
        
        <p>New elements were created for new HTML5 form inputs.</p>
<pre>
<strong>$form->addElement('number', 'number', array(
    'label'       => 'Number',
    'min'         => 1,
    'max'         => 10
));

$form->addElement('range', 'range', array(
    'label'       => 'Range',
    'min'         => 1,
    'max'         => 5,
    'prepend'     => 1,
    'append'      => 5
));

$form->addElement('url', 'site', array('label' => 'Site'));
$form->addElement('email', 'email', array('label' => 'E-mail'));
$form->addElement('color', 'color', array('label' => 'Color'));
$form->addElement('date', 'date', array('label' => 'Date'));
$form->addElement('time', 'time', array('label' => 'Time'));
$form->addElement('datetime', 'datetime', array('label' => 'Datetime'));
$form->addElement('month', 'month', array('label' => 'Month'));
$form->addElement('week', 'week', array('label' => 'Week'));
$form->addElement('search', 'search', array('label' => 'Search'));
</strong></pre>   

    <p>And a new element was created for <a href="http://getbootstrap.com/css/#forms-controls-static" target="_blank">Bootstrap's form static text</a>.</p>
        
<pre>
<strong>$form->addElement('staticText', 'uneditable', array(
    'label' => 'Static text', 
    'value' => 'You can not edit this text'
));
</strong></pre>

        <p>Add the form the the view.</p>
<pre>
<strong><?php echo $this->escape('$this->view->form = $form;'); ?></strong>
</pre>      
    
        <p>Now, print the form in your view and it will be rendered in bootstrap's format.</p>
<pre>
<strong><?php echo $this->escape('<?php echo $this->form; ?>'); ?></strong>
</pre>      
    
    <div class="panel panel-default">
        <div class="panel-heading">Output</div>
        <div class="panel-body">
            <?php echo $this->form; ?>
        </div>
    </div>
        
    <div class="jumbotron text-center">
        <h2>Enjoy!!! <span class="glyphicon glyphicon-thumbs-up"></span></h2>
    </div>
        
    </article>

    <nav class="col-sm-2" id="affix-nav">
        <ul class="nav nav-pills nav-stacked affix affix-top">
            <li class="active"><a href="#howtouse">How to use</a></li>
            <li><a href="#alerts">Alerts</a></li>
            <li><a href="#carousel">Carousel</a></li>
            <li><a href="#pagination">Pagination</a></li>
            <li><a href="#navigation">Navigation</a></li>
            <li><a href="#breadcrumbs">Breadcrumbs</a></li>
            <li><a href="#forms">Forms</a></li>
        </ul>
    </nav>
    
</div>